msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2024-08-18 09:06+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI +ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0\n"
"Language-Code: en\n"
"Language-Name: English\n"
"Preferred-Encodings: utf-8 latin1\n"
"Domain: DOMAIN\n"

#: ../validators/IdValidator.py:26
msgid "Id $id is already in use"
msgstr "आईडी $id पहले से ही उपयोग में है"

#: ../validators/IdValidator.py:17
msgid "Spaces are not allowed in ids"
msgstr "आईडी में अंतरिक्ष अनुमत नहीं हैं"

#: ../validators/RegexValidator.py:46
msgid "Validation failed($name): $value of type $type, expected 'string'"
msgstr "मान्यीकरण असफल ($name): $value प्रकार $type, 'स्ट्रिंग' की अपेक्षा"

#: ../validators/RegexValidator.py:65
msgid "Validation failed($name): '$value' $errmsg"
msgstr "मान्यीकरण असफल ($name): '$value' $errmsg"

#: ../validators/EmptyValidator.py:45
msgid "Validation failed($name): '$value' is not empty."
msgstr "मान्यीकरण असफल ($name): '$value' खाली नहीं है।"

#: ../validators/RangeValidator.py:41
msgid "Validation failed($name): '$value' out of range($min, $max)"
msgstr "मान्यीकरण असफल ($name): '$value' सीमा से बाहर ($min, $max)"

#: ../validators/SupplValidators.py:103
msgid "Validation failed($name): could not convert $value to a date."
msgstr "मान्यीकरण असफल ($name): $value को तारीख में परिवर्तित नहीं किया जा सका।"

#: ../validators/RangeValidator.py:33
msgid "Validation failed($name): could not convert '$value' to number"
msgstr "मान्यीकरण असफल ($name): '$value' को संख्या में परिवर्तित नहीं किया जा सका"

#: ../validators/SupplValidators.py:94
msgid "Validation failed($name): value is empty ($value)."
msgstr "मान्यीकरण असफल ($name): मान खाली है ($value)।"

#: ../validators/SupplValidators.py:71
msgid "Validation failed($name: Uploaded data is too large: ${size}MB (max ${max}MB)"
msgstr "मान्यीकरण असफल ($name: अपलोड किए गए डेटा बहुत बड़ा है: ${size}MB (अधिकतम ${max}MB)"

#: ../validators/BaseValidators.py:51
msgid "contains unprintable characters"
msgstr "अप्रिंटेबल अक्षरों को समाहित करता है"

#: ../validators/BaseValidators.py:37
msgid "is not a decimal number."
msgstr "एक दशमलव संख्या नहीं है।"

#: ../validators/BaseValidators.py:95
msgid "is not a valid email address."
msgstr "एक मान्य ईमेल पता नहीं है।"

#: ../validators/BaseValidators.py:74
msgid "is not a valid international phone number."
msgstr "एक मान्य अंतर्राष्ट्रीय फोन नंबर नहीं है।"

#: ../validators/BaseValidators.py:88
msgid "is not a valid url."
msgstr "एक मान्य यूआरएल नहीं है।"

#: ../validators/BaseValidators.py:66
msgid "is not a valid us phone number."
msgstr "एक मान्य यूएस फोन नंबर नहीं है।"

#: ../validators/BaseValidators.py:81
msgid "is not a valid zip code."
msgstr "एक मान्य ज़िप कोड नहीं है।"

#: ../validators/BaseValidators.py:58
msgid "is not a well formed SSN."
msgstr "एक अच्छी तरह से निर्मित एसएसएन नहीं है।"

#: ../validators/BaseValidators.py:44
msgid "is not an integer."
msgstr "एक पूर्णांक नहीं है।"

#: ../validators/BaseValidators.py:109
msgid "this name is not a valid identifier"
msgstr "यह नाम एक वैध पहचानकर्ता नहीं है"

#: ../validators/ExpressionValidator.py:94
msgid "validation failed, expr was:$expr"
msgstr "सत्यापन विफल रहा, expr था:$expr"
