msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2024-08-18 09:06+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI +ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0\n"
"Language-Code: en\n"
"Language-Name: English\n"
"Preferred-Encodings: utf-8 latin1\n"
"Domain: DOMAIN\n"

#: ../validators/IdValidator.py:26
msgid "Id $id is already in use"
msgstr "L'id $id est déjà utilisé."

#: ../validators/IdValidator.py:17
msgid "Spaces are not allowed in ids"
msgstr "Les espaces ne sont pas autorisées dans les ids."

#: ../validators/RegexValidator.py:46
msgid "Validation failed($name): $value of type $type, expected 'string'"
msgstr "La validation a échoué ($name) : $value de type $type, attendu « string »."

#: ../validators/RegexValidator.py:65
msgid "Validation failed($name): '$value' $errmsg"
msgstr "La validation a échoué ($name) : « $value » $errmsg."

#: ../validators/EmptyValidator.py:45
msgid "Validation failed($name): '$value' is not empty."
msgstr "La validation a échoué ($name) : « $value » n'est pas vide."

#: ../validators/RangeValidator.py:41
msgid "Validation failed($name): '$value' out of range($min, $max)"
msgstr "La validation a échoué ($name) : « $value » hors de l'intervalle ($min, $max)."

#: ../validators/SupplValidators.py:103
msgid "Validation failed($name): could not convert $value to a date."
msgstr "La validation a échoué ($name) : n'a pu convertir $value en une date."

#: ../validators/RangeValidator.py:33
msgid "Validation failed($name): could not convert '$value' to number"
msgstr "La validation a échoué ($name) : n'a pu convertir « $value » en nombre."

#: ../validators/SupplValidators.py:94
msgid "Validation failed($name): value is empty ($value)."
msgstr "La validation a échoué ($name) : la valeur est vide ($value)."

#: ../validators/SupplValidators.py:71
msgid "Validation failed($name: Uploaded data is too large: ${size}MB (max ${max}MB)"
msgstr "La validation a échoué ($name) : les données téléversées sur le serveur sont trop volumineuses : ${size}Mo (max ${max}Mo)."

#: ../validators/BaseValidators.py:51
msgid "contains unprintable characters"
msgstr "contient des caractères non imprimables."

#: ../validators/BaseValidators.py:37
msgid "is not a decimal number."
msgstr "n'est pas un nombre décimal."

#: ../validators/BaseValidators.py:95
msgid "is not a valid email address."
msgstr "n'est pas une adresse courriel valide."

#: ../validators/BaseValidators.py:74
msgid "is not a valid international phone number."
msgstr "n'est pas un numéro de téléphone international valide."

#: ../validators/BaseValidators.py:88
msgid "is not a valid url."
msgstr "n'est pas une url valide."

#: ../validators/BaseValidators.py:66
msgid "is not a valid us phone number."
msgstr "n'est pas un numéro de téléphone états-unien valide."

#: ../validators/BaseValidators.py:81
msgid "is not a valid zip code."
msgstr "n'est pas un code postal valide."

#: ../validators/BaseValidators.py:58
msgid "is not a well formed SSN."
msgstr "n'est pas un SSN bien formé."

#: ../validators/BaseValidators.py:44
msgid "is not an integer."
msgstr "n'est pas un entier."

#: ../validators/BaseValidators.py:109
msgid "this name is not a valid identifier"
msgstr "Ce nom n'est pas un identifiant valide."

#: ../validators/ExpressionValidator.py:94
msgid "validation failed, expr was:$expr"
msgstr "La validation a échoué, l'expression était : $expr."
